# _config.yml
source: docs
destination: docs/_site

# Other optional configurations
title: My Jekyll Site
email: your-email@example.com
description: >- # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://yourdomain.com" # the base hostname & protocol for your site

markdown: kramdown
theme: jekyll-theme-primer

# Build settings
future: false
verbose: true
